language: node_js
node_js:
- "8"
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
- chmod u+x trav.sh
install:
- npm install
- npm install mocha
script:
- ./trav.sh
