language: node_js
node_js:
- "8"
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
  - /Backend/node_modules
before_install:
- chmod u+x trav.sh
script:
- ./trav.sh
